### ISSUE TITLE
The resize does not work when a column is not visible.

### ISSUE THREAD

**Issue by omerman** [Silvacom/colResize#7]
When you hide a column, it's impossible to resize the nearby columns properly.
http://jsfiddle.net/bjsk18dt/1/

**Comment by StephaniesHusband** [comment]
Did this get resolved? Why was this closed? I'm seeing same issue.

**Comment by prog8** [comment]
I also have the same issue. Any news here?

**Comment by otisg** [comment]
Same here.  @omerman - is this basically closed as "Won't Fix" because it just cannot be done?

**Comment by 1Jesper1** [comment]
This issue is still in the latest release? I'm using colResize with colVis and ColReorder.

FIX: Version 0.0.6 works.
This commit: 
https://github.com/Silvacom/colResize/commit/703343f02783af4417247f5218d43b9d47d96d6e

UPDATE: Request a pull to merge https://github.com/1Jesper1/colResize/commit/9bddf7509ea305c1babbc760bb63285f976c8ddb into master. 

I used the data-column-index attribute to get column indexes as also seen in _fnMouseMove function.

**Comment by dykstrad** [comment]
Thanks for the update.
